ipynb-filters: [nbdev_filter]

project:
  type: website
  output-dir: _docs
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4

website:
  title: "test_image_embed"
  site-url: "https://hamelsmu.github.io/test_image_embed"
  description: "Description: Test out IPython.display.Image(embed=True) in nbdev."
  twitter-card: true
  open-graph: true
  reader-mode: true
  repo-branch: master
  repo-url: "https://github.com/hamelsmu/test_image_embed"
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: "https://github.com/hamelsmu/test_image_embed"
  sidebar:
    style: "floating"

metadata-files: 
  - sidebar.yml
  - custom.yml
