# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/test_image_embed',
                'doc_host': 'https://hamelsmu.github.io',
                'git_url': 'https://github.com/hamelsmu/test_image_embed',
                'lib_path': 'test_image_embed'},
  'syms': {'test_image_embed.core': {'test_image_embed.core.foo': ('core.html#foo', 'test_image_embed/core.py')}}}